<?php
	return array(
			'system/userlist'         	=> array('canshow'=>1,'name'=>'User List'),
			'system/useradd'          	=> array('canshow'=>0,'name'=>'Add Users'),
			'system/usermod'          	=> array('canshow'=>0,'name'=>'Edit Users'),
			'system/password'        	=> array('canshow'=>1,'name'=>'Password Change'),
			'system/powerlist'        	=> array('canshow'=>1,'name'=>'Power Manager'),
			'system/poweradd'         	=> array('canshow'=>0,'name'=>'Add Power'),
			'system/powermod'         	=> array('canshow'=>0,'name'=>'Edit Power'),
			'system/grouplist'        	=> array('canshow'=>1,'name'=>'Group Manager'),
			'system/groupadd'         	=> array('canshow'=>0,'name'=>'Add Group'),
			'system/groupmod'         	=> array('canshow'=>0,'name'=>'Edit Group'),
			'system/groupdel'         	=> array('canshow'=>0,'name'=>'Delete Group'),
			'system/grouppowerlist'   	=> array('canshow'=>1,'name'=>'Group Power Manager'),
			'system/grouppoweradd'    	=> array('canshow'=>0,'name'=>'Add Group Power'),
			'system/grouppowermod'    	=> array('canshow'=>0,'name'=>'Edit Group Power'),
			'system/grouppowerdel'    	=> array('canshow'=>0,'name'=>'Delete Group Power'),
			'system/systemlog'   		=> array('canshow'=>1,'name'=>'System Logs'),
			'system/config'   			=> array('canshow'=>1,'name'=>'System Config'),
			'system/personedit'		=> array('canshow'=>1,'name'=>'Edit Personal Info'),
			'advertiser/index'   		=> array('canshow'=>1,'name'=>'Advertiser List'),
			'advertiser/create'   		=> array('canshow'=>1,'name'=>'Create Advertiser'),
			'advertiser/testlink'   		=> array('canshow'=>1,'name'=>'Advertiser Test Link'),
			'advertiser/edit'   		=> array('canshow'=>0,'name'=>'Edit Advertiser'),
			'advertiser/update'   		=> array('canshow'=>0,'name'=>'Update Advertiser'),
			'affiliates/index'   		=> array('canshow'=>1,'name'=>'Affiliate List'),
			'affiliates/create'   		=> array('canshow'=>1,'name'=>'Create Affiliate'),
			'affiliates/createaff'   		=> array('canshow'=>1,'name'=>'Create New Affiliate'),
			'affiliates/edit'   		=> array('canshow'=>0,'name'=>'Edit Affiliate'),
			'affiliates/update'   		=> array('canshow'=>0,'name'=>'Update Affiliate'),
			'offer/list'   				=> array('canshow'=>1,'name'=>'Offer List'),
			'offer/add'   				=> array('canshow'=>1,'name'=>'Add Offer'),
			'offer/offerdetail'   		=> array('canshow'=>0,'name'=>'Offer Detail'),
			'offer/statistics'   		=> array('canshow'=>1,'name'=>'Offer Statistics'),
			'offer/editcaps'			=> array('canshow'=>0,'name'=>'Edit Offer Caps'),
			'offer/offerthumbnail'		=> array('canshow'=>0,'name'=>'Add thumbnail'),
			'offer/addpixels'   		=> array('canshow'=>0,'name'=>'Add Pixels'),
			'offer/toexcel'				=> array('canshow'=>0,'name'=>'To Excel'),
			'pixels/list'   		    => array('canshow'=>1,'name'=>'Pixels List'),
			'pixels/urltest'   		    => array('canshow'=>0,'name'=>'Test PixelsURl'),
			'pixels/pixelsedit'   		=> array('canshow'=>0,'name'=>'Edit Pixels'),
			'pixels/pixelsdelete'   	=> array('canshow'=>0,'name'=>'Delete Pixels'),
			'offer/deleteaccount'   	=> array('canshow'=>0,'name'=>'Delete Affiliate Income'),
			'offer/editaccount'   		=> array('canshow'=>0,'name'=>'Edit Affiliate Income'),
			'offer/updateaccount'   	=> array('canshow'=>0,'name'=>'Update Affiliate Income'),
			'offer/editpayout'   		=> array('canshow'=>0,'name'=>'Edit Offer Payout'),
			'offer/updatepayout'   		=> array('canshow'=>0,'name'=>'Update Offer Payout'),
			'offer/updatedetail'		=> array('canshow'=>0,'name'=>'Update Detail'),
			'offer/editdetail'			=> array('canshow'=>0,'name'=>'Edit Detail'),
			'offer/whitelist'			=> array('canshow'=>0,'name'=>'White List Manager'),
			'offer/updatecut'			=> array('canshow'=>0,'name'=>'Cut Num Edit'),
			'offer/whitelistadd'		=> array('canshow'=>0,'name'=>'White List Add'),
			'offer/whitelistedit'		=> array('canshow'=>0,'name'=>'White List Edit'),
			'offer/whitelistdel'		=> array('canshow'=>0,'name'=>'White List Delete'),
			'affiliateapi/getlist'		=> array('canshow'=>0,'name'=>'Affiliate Get Offer List'),
			'affiliateapi/tokenlist'	=> array('canshow'=>1,'name'=>'Get token List'),
			'affiliateapi/addwhite'		=> array('canshow'=>1,'name'=>'Add Affiliate WhiteList'),
			'affiliateapi/gettoken'		=> array('canshow'=>0,'name'=>'Get token'),
			'affiliateapi/deletewhite'	=> array('canshow'=>0,'name'=>'Delete token'),
			'system/sendemail'			=> array('canshow'=>1,'name'=>'SendEmail'),
			'offer/mnclicklist'			=> array('canshow'=>1,'name'=>'Imitation Offer Click Manager'),
			'offer/mnclickadd'			=> array('canshow'=>0,'name'=>'Imitation Offer Click Add'),
			'offer/mnclickedit'			=> array('canshow'=>0,'name'=>'Imitation Offer Click Edit'),
			'offer/mnclickupdatestatus'	=> array('canshow'=>0,'name'=>'Imitation Offer Click Delete'),
			'offer/typemanager'		=> array('canshow'=>1,'name'=>'TypeManager'),
			'report/dailyreport'		=> array('canshow'=>1,'name'=>'Daily Report'),
			'report/affreport'		=> array('canshow'=>0,'name'=>'Affiliate Report'),
			'offer/offercut'		=> array('canshow'=>0,'name'=>'Affiliate Offer Cut'),
			'offer/editoffercut'		=> array('canshow'=>0,'name'=>'Affiliate Offer Cut Edit'),
			'offer/getcountriesinfo'		=> array('canshow'=>0,'name'=>'Get Countries Info'),
			'offer/updatelogs'		=> array('canshow'=>1,'name'=>'Update Logs'),
			'system/message'		=> array('canshow'=>1,'name'=>'Message'),
			'system/getmsg'		=> array('canshow'=>1,'name'=>'Get System Message'),
			'offer/changerecommend'		=> array('canshow'=>0,'name'=>'Change Recommend'),
			'advertiser/buildurl'		=> array('canshow'=>1,'name'=>'Build Trancklink'),
			'report/crreport'		=> array('canshow'=>1,'name'=>'CRReport'),
			'report/reportdetail'		=> array('canshow'=>1,'name'=>'Report Detail'),
			'report/excelexport'		=> array('canshow'=>1,'name'=>'Excel Export'),
			'report/dl'		=> array('canshow'=>1,'name'=>'Delete Report'),
			'report/saveexcel'		=> array('canshow'=>0,'name'=>'Report Save Excel'),
			'offer/jumpoffer'		=> array('canshow'=>1,'name'=>'Offer Jump'),
			'system/timestamp' =>array('canshow'=>1,'name'=>'Time Stamp'),
			'offer/jumptask' => array('canshow'=>1,'name'=>'Jump Task'),
			'affiliates/payment' => array('canshow'=>1,'name'=>'Payment Info'),
			'payment/invoice' => array('canshow'=>1,'name'=>'Payments'),
			'payment/setinvoice' => array('canshow'=>1,'name'=>'Set Invoice'),
			'payment/check' =>array('canshow'=>0,'name'=>'Check Payments'),
			'payment/uploadpdf' =>array('canshow'=>0,'name'=>'Upload PDF'),
			'payment/viewPDF' =>array('canshow'=>0,'name'=>'Show PDF'),
			'payment/sitepayoutinfo' => array('canshow'=>1,'name'=>'Site Payments'),
			'payment/detail' =>array('canshow'=>0,'name'=>'Payment Detail'),
			'payment/savepayout' =>array('canshow'=>0,'name'=>'Payment Payout Save'),
			'payment/checkall' =>array('canshow'=>0,'name'=>'Payment Check All'),
			'payment/building' =>array('canshow'=>1,'name'=>'Payment Building'),
			'payment/invoicepay' =>array('canshow'=>0,'name'=>'Payment Invoice Info'),
			'payment/savetotalpayment' =>array('canshow'=>0,'name'=>'Payment Save Total Payment'),
			'offer/offershow'=>array('canshow'=>1,'name'=>'Affiliate Offer Control'),
			'offer/offerlistshow'=>array('canshow'=>1,'name'=>'Affiliate Offer List'),
			'system/addmessage'		=> array('canshow'=>1,'name'=>'Add Message'),
			'system/addmessage&msg_type=0'		=> array('canshow'=>1,'name'=>'System Message'),
			'system/addmessage&msg_type=1'		=> array('canshow'=>1,'name'=>'Apply Message'),
			'payment/outputexcel'		=> array('canshow'=>0,'name'=>'Download Payments Excel'),
			'site/index' =>array('canshow'=>1,'name'=>'Site List'),
			'site/edit' =>array('canshow'=>1,'name'=>'Information'),
			'site/dl' =>array('canshow'=>0,'name'=>'Site Delete'),
			'site/addrel' =>array('canshow'=>0,'name'=>'Site Add Rel'),
			'site/create' =>array('canshow'=>0,'name'=>'Site Create'),
			'site/affiliatelist' =>array('canshow'=>1,'name'=>'Site Affiliate List'),
			'site/deletesite' =>array('canshow'=>0,'name'=>'Delete Site'),
			'report/downloadcrexcel' =>array('canshow'=>0,'name'=>'Download CR Excel'),
			'report/realtimereport' =>array('canshow'=>1,'name'=>'Real Time Report'),
			'payment/downloadpayment' =>array('canshow'=>0,'name'=>'Download Payment'),
			'payment/paymenttotal' =>array('canshow'=>1,'name'=>'Payment Total'),
			'payment/sendandpay' =>array('canshow'=>0,'name'=>'Send And Pay Payment Total'),
	);
?>