<?php

/**
 * Created by PhpStorm.
 * User: land.zhang
 * Date: 2016/8/20
 * Time: 17:35
 */
class UserController extends Controller
{
    public $layout = '//layouts/sidebar';
    public function filters()
    {
        return parent::filters(); // TODO: Change the autogenerated stub
    }

    public function actionList(){
        $criteria = new CDbCriteria();
        $dataProvider = new CActiveDataProvider('user',array('criteria'=>$criteria));
        $this->render('list',array('dataProvider'=>$dataProvider));
    }
}